name: AWS SES CI/CD

on:
  pull_request:
  push:
    branches:
      - master
      - prerelease

jobs:
  build-application:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Bump Application Version and Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          default_prerelease_bump: prerelease
          release_branches: master
          pre_release_branches: prerelease
          append_to_pre_release_tag: prerelease

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: awsses_${{ steps.tag_version.outputs.new_tag }}
          if-no-files-found: ignore
          path: |
            api
            data
            extensions
            hooks
            interface
            modules
            setup
            sources
            tasks
            widgets
            Application.php